<?php
/**
 * psp-import-vaardigheden.php
 * Importeer vaardigheden uit Poule Excel → WP user meta
 * URL: ?sleutel=pspvaardigheden2026
 * Uitvoeren: ?sleutel=pspvaardigheden2026&run=1
 */
$sleutel = $_GET['sleutel'] ?? '';
if ($sleutel !== 'pspvaardigheden2026') { header('Location: /'); exit; }
require_once dirname(__FILE__) . '/../../../wp-load.php';
$uitvoeren = isset($_GET['run']) && $_GET['run'] === '1';

// Data uit Poule Excel
$poule_data = [
  ['Hanne Algra','hannealgra@gmail.com','06 30616332','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "opmerkingen": "13 mrt t/m half juni op reis | Wil geen HKL/BW meer"}'],
  ['Walid Alkodmani','aaledw@gmail.com','06-38868668','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Nick Anbergen','nick0728@live.nl','06-29859298','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "housekeeping": "1", "cycloon": "1", "opmerkingen": "Alleen BW daar hij in Stadskanaal woont, voor flex in Groningen is het betreft tijd en afstand niet te doen"}'],
  ['Luz Perez Batista','luzperezbatista55@gmail.com','06-10182687','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Hugo Beckers','hugo.beckers06@gmail.com','06-49936676','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "housekeeping": "1", "opmerkingen": "vanaf 5 jan weer bsb"}'],
  ['Kim van den Belt','kimvandenbelt4@icloud.com','06-24671080','{"nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "photonis": "1", "housekeeping": "1", "opmerkingen": "Wk 11 op wintersport", "barista": "1"}'],
  ['Harnet Beyene','harnetbeyene21@outlook.com','Bellen: 0686232525 / WhatsApp:06-48131979','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "photonis": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "VAKANTIE 0907-3107"}'],
  ['Mariame Bofaya','mariame.bofaya@yahoo.com','06-19849798','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Lasse van Bokhoven','lassevanbokhoven@gmail.com','06-22322103','{"rijbewijs": "bezig", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "opmerkingen": "2 feb t/m 9 mei buitenland | Geen Bonte Wever meer"}'],
  ['Tijs Boonman','t.boonman@hotmail.com','06-30409856','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Maud Boschker','maud.boschker@gmail.com','06-18203191','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "beijk_wolvega": "1", "catering": "1", "ass_keuken": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Vincent Brouwer','vbrouwer@live.nl','06-30587447','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "photonis": "1", "orderpicker": "1", "housekeeping": "1"}'],
  ['Egge Buijink','eggebuijink@gmail.com','06-82005142','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "opmerkingen": "Assen i.o. hangt er van af of hij met OV of auto gaat, Garnwerd ivm afstand. GEEN BW", "afwas": "1"}'],
  ['Yaro Bult','yaro@ziggo.nl','06-83107110','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "housekeeping": "1"}'],
  ['Anniek Bultjes','anniek@bultje.nl','06-80136540','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "drukt met studie, begin apr weer contact"}'],
  ['Amber Burbach','amber.burbach@icloud.com','06-30199659','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "photonis": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "tentamenweek | app 1603 of ze forms wil invullen anders non actief heeft ook andere bijbaan | MD 28-03: heeft het druk ivm tentamens"}'],
  ['Melba Chilaúle','melba.chilaule@gmail.com','06 -84601080','{"nl_spreken": "1", "nl_verstaan": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief | Vriendin van Menno van der Velde, hij heeft auto | GEEN HK MEER"}'],
  ['Daan Corzaan','pdcorzaan@gmail.com','06-39679514','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Treffer Dekker','t9dekker@gmail.com','06-24605385','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Last minute altijd bellen, referentie zei (zijn moeder) dat hij vaak last minute zijn planning duidelijk heeft en wellicht alsnog kan werken", "fysiek_zwaar": "1"}'],
  ['Floor Dijk van','floorlvandijk@gmail.com','06-18713759','{"rijbewijs": "BA", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "opmerkingen": "Vakantie | Nee, bedankt!", "housekeeping": "1"}'],
  ['Marco Dijk van','marcovandijk989@gmail.com','06-47668363','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Ruben Dijk van','ruben.daan.van.dijk@gmail.com','06-46031779','{"rijbewijs": "?", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "photonis": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "barista": "1", "opmerkingen": "bsb deze week hangt af van wanneer opa wordt cremeert"}'],
  ['Jelte Folkertsma','jeltefolkertsma06@gmail.com','06-15203678','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1", "opmerkingen": "Fulltime fysio stage | Fulltime fysio stage, ALLEEN ZATERDAGS BSB"}'],
  ['Adrians Formanickis','formanickisadrians@gmail.com','06-19276890','{"rijbewijs": "BS", "nl_verstaan": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1"}'],
  ['Yannick Fraanje','yanfraanje@gmail.com','06-17077803','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "orderpicker": "1", "schoonmaak": "1", "opmerkingen": "Alleen diensten in Groningen, wil niet meer naar Assen"}'],
  ['Téa Froger','froger.tea1@gmail.com','06-16170712','{"nl_spreken": "1", "catering": "1", "housekeeping": "1", "opmerkingen": "Van week 50 t/m week 1 niet bsb, gaat naar huis!"}'],
  ['Mariantonietta Fumarola','mfumarola89@gmail.com','00-324883558','{"rijbewijs": "nee", "housekeeping": "1"}'],
  ['Rafael Funke','rcmfunke@gmx.de','0049 176 568 570 39','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "barista": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "vanaf wk 7 voor drie weken niet in Groningen | 1/2 x per maand inplannen ivm studie drukt 04122025 EL: hij geef het zelf ook aan via de forms"}'],
  ['Merel Gelder Van','merelvgelder@hotmail.com','06-83112578','{"rijbewijs": "Bezig", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "housekeeping": "1", "cycloon": "1"}'],
  ['Lara Goede de','laradeg05@gmail.com','06-11839088','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "opmerkingen": "na kerstvakantie weer bsb"}'],
  ['Iris Haan de','irisdehaan2007@gmail.com','06-10942107','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Sam Haan de','sjdh2004@gmail.com','06-30339976','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "photonis": "1", "afwas": "1", "orderpicker": "1", "housekeeping": "1"}'],
  ['Mahmoud Hassan','mahmoudkk55m@gmail.com','06-39539280','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Alleen in het weekend bsb. SPREEK WEL NEDERLANDS MAAR MOEIZAAM, SOMS LASTIG TE BEGRIJPEN"}'],
  ['Pim Heijckmann','pimheijckmann@gmail.com','06-15443434','{"rijbewijs": "bezig", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Febe Hellinga','febe.hellinga@gmail.com','06-25538212','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Anne-Sophie Herwijnen van','asvanherwijnen@live.nl','06-23874338','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "orderpicker": "1", "housekeeping": "1"}'],
  ['Zahra Heydari','zahraheydari2005@gmail.com','06-84026992','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "housekeeping": "1", "opmerkingen": "Alleen vrijdag en zaterdag bsb voor horeca/catering | ALLEEN BSB VOOR FESTIVALS EN EVENEMENTEN", "plateau": "1"}'],
  ['Lucia Hoeffnagel','l.hoeffnagel@gmail.com','06-23397948','{"rijbewijs": "BA", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Julia Hoevenaar','hoevenaarjulia@gmail.com','06-83897804','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "photonis": "1", "schoonmaak": "1", "stijlzinnig": "1", "opmerkingen": "20 feb t/m 9 mrt op vakantie | Als Julia elke week blijft werken, moet ze per 08-03 over naar fase B. Geen HK meer | Geen HK meer", "barista": "1"}'],
  ['Cecile Hoving','cecile.hoving@gmail.com','06-40775585','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1", "opmerkingen": "vakantie | Alleen naar HK in vakanties | Alleen in Groningen, in overleg Assen of Roden incl HK in haar vakantie", "barista": "1"}'],
  ['Mander Huiskes','manderhuiskes@gmail.com','06-46305819','{"nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Evt op vrijdag nog werken naar uren FJ, niet altijd bsb ivm rijles"}'],
  ['arianna Ionas','a.ionas@student.rug.nl','+31 620556833','{"rijbewijs": "nee", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "VANAF SEPT VASTE UREN BAKKER VA 17 UUR"}'],
  ['Astrid Jager','astridj.jager@gmail.com','06-37297618','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "plateau": "1", "catering": "1", "schoonmaak": "1", "stijlzinnig": "1", "opmerkingen": "Niet meer naar Photonis, Leander niet blij met haar", "bier_tappen": "1", "photonis": "1"}'],
  ['Tirzah de Jong','tirzahdejong24@gmail.com','06-23153122','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "opmerkingen": "vanaf 9 feb meer bsb ivm afgeronde stage | NIET MEER NAAR HK"}'],
  ['Nick Koenderink','n.a.koenderink@gmail.com','06-51694347','{"rijbewijs": "?", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Alicia Kruidhof Cervantes','ikbenaliciayeah@outlook.com','06-33306364','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief"}'],
  ['Zoë Kuijck van','zoe.van.kuijck@gmail.com','06-81708076','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "stijlzinnig": "1", "cycloon": "1", "opmerkingen": "heel wk 10 niet bsb | Vond bediening/catering Beijk RUG erg leuk, vaker voor vragen. Geen Bonte Wever meer!"}'],
  ['Kirsten Kuperus','kirstenkuperus@gmail.com','06-14119070','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "lichte hersenschudding", "barista": "1"}'],
  ['Caya Mei van der','cayavandermei@icloud.com','06 – 15524234','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Eva Mesu','eva.fee.mesu@gmail.com','06-23985676','{"rijbewijs": "BS, maar is gewend aan automaat dus liever geen schakel meer", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "wk 9 vakantie | en vakantie week 9"}'],
  ['Julian Moek','julian.moek@gmail.com','06-41312772','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "niet bsb ivm tentamen"}'],
  ['Natalia Neaga','natinega23@gmail.com','+40 720 026 902','{"rijbewijs": "nee", "nl_verstaan": "1", "catering": "1", "housekeeping": "1"}'],
  ['Jasmijn Nieuwkoop van','jasmijn.vannieuwkoop@gmail.com','06-83705094','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Redelijk veel bsb komende tijd"}'],
  ['Ole-Pepijn - van \'t Noordende','olepepijnvtn@gmail.com','06-51018878','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "catering": "1", "orderpicker": "1", "opmerkingen": "MD: 0903: druk met studie,kan af en toe wel werken"}'],
  ['Julian Overhorst','julianoverhorst@outlook.com','06-10413611','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "afwas": "1", "schoonmaak": "1", "stijlzinnig": "1", "opmerkingen": "Wil niet meer in de afwas bij CdKW"}'],
  ['Yeva Plakhotna','plahotna.evaa@gmail.com','06-57338282','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "plateau": "1", "catering": "1", "afwas": "1"}'],
  ['Sophie Pol van der','sophievdp05@gmail.com','06-53632680','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "opmerkingen": "vanaf feb half jaar in Milaan voor studie"}'],
  ['Maria Putters','mjpputters@gmail.com','06-57198671','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "tentamens"}'],
  ['Wiite de Rijk','wittederijk@hotmail.com','06 2212 8630','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Maarten Roos','maartensimonroos@icloud.com','06-49168026','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "afwas": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "cycloon": "1", "opmerkingen": "6 t/m 16 mrt op vakantie"}'],
  ['Mila Ruchti','milaruchti@hotmail.com','06-57235150','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "cycloon": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief"}'],
  ['Jente Schirm','jenteschirm@gmail.com','06-57374009','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "opmerkingen": "Voorkeur Groningen, alles i.o. Assen alleen bij lange dienst!!"}'],
  ['Nick Schraa','nickschraa123@gmail.com','06-16854716','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "photonis": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "kerstvakantie in Almelo | geen horeca ervaring maar wil dit wel leren"}'],
  ['Manon Schuurs','manon.schuurs2003@gmail.com','06-18169180','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "orderpicker": "1", "housekeeping": "1"}'],
  ['Adrian Sirbu','adisirbu2006@gmail.com','06-26284376','{"housekeeping": "1", "cycloon": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief | NIET TERUG BW, wil maar 2 dagen werken!!!", "rijbewijs": "nee"}'],
  ['Léon Spa','lbdspa@gmail.com','06-12657099','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "ass_keuken": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Wintersport 31 jan t/m 7 feb | Loopt stage", "horeca_toppers": "1", "barista": "1"}'],
  ['Luuk van Spil','luuk.van.spil@kpnmail.nl','06-30931633','{"rijbewijs": "?", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Druk met andere baan en leven, eind mrt weer contact dan evt uit de poule | Werkt 30 uur per week bij MediaMarkt (di, do en vr werkdagen) Ma en woe bsb voor PS"}'],
  ['Simone Stagnitto','simone.stagnitto@gmail.com','0039-3298014598','{"rijbewijs": "nee", "nl_verstaan": "1", "bar": "1", "borden_3": "1", "beijk_wolvega": "1", "catering": "1", "barista": "1", "opmerkingen": "23 dec t/m 5 jan niet in Groningen"}'],
  ['Lysanne Stoop','lysannestoop@gmail.com','06-57783254','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "cycloon": "1", "opmerkingen": "Tijdelijke baan van 2/3 dagen per week in week 9 en heel mrt"}'],
  ['Wout Terlingen','wout-terlingen@hotmail.com','06-21651131','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "orderpicker": "1", "opmerkingen": "NIET NAAR RADIAL, 20 tot 24 uur meer in overleg"}'],
  ['Bas Tervoort','bastervoort0@gmail.com','06-11805615','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "opmerkingen": "8 t/m 18 apr op vakantie en 28 apr t/m 3 mei ook", "bar": "1", "bier_tappen": "1"}'],
  ['Stijn Timmermans','shatimmermans@gmail.com','06-27302983','{"rijbewijs": "BS maar gewend aan automaat dus inkomen schakel", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "housekeeping": "1", "bar": "1", "bier_tappen": "1", "photonis": "1", "afwas": "1", "opmerkingen": "druk met tentamens tot eind jan | Nee, bedankt!"}'],
  ['Daniel Tipping','drtipping2007@gmail.com','06-28162869','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Nina ASSEN Tyler','ninatyl@hotmail.com','06-39373709','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "catering": "1", "photonis": "1", "barista": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief | Vast bij Pears maar wel benaderen voor horeca"}'],
  ['Robbin Veen','robbinveen@hotmail.com','06-14568520','{"rijbewijs": "ja", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "photonis": "1", "housekeeping": "1", "opmerkingen": "heel wk 8 niet bsb"}'],
  ['Laure Veerman','laureveerman@icloud.com','06-11151783','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "week 13/14/15 tentamens, evt tussendoor wel werken"}'],
  ['Gus Vegchel Van','gusvanvegchel@gmail.com','06-23096067','{"nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief"}'],
  ['Menno Velde van der','mennovandervelde@live.nl','06- 38745874','{"rijbewijs": "?", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "housekeeping": "1", "opmerkingen": "uit poule gehaald, nooit bsb. Na maand geen contact met onsopgenomen op non-actief | Vriend van Melba, heeft auto"}'],
  ['Ezekiel Vita','e.vita26@hotmail.com','06-31981014','{"rijbewijs": "bezig", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Kirsten Vliem','kirstenvliem@gmail.com','06-22339318','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1"}'],
  ['Sam Vorsteveld','samvorsteveld@icloud.com','06-30648650','{"nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "orderpicker": "1", "opmerkingen": "Doordeweeks studie, alleen weekenden en avonden bsb"}'],
  ['Jasmijn Wagenaar','jasmijnwagenaar@gmail.com','06-14796032','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Lotte de Wagt','lotte.dewagt@gmail.com','06-44224015','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "beijk_wolvega": "1", "catering": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "13 mrt t/m half juni op reis"}'],
  ['Ilse Wal van der','ils1312@hotmail.nl','06-40636890','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Lea van Wijk','leavanwijk@gmail.com','06-16599762','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Druk met studie, geeft seintje als ze weer wilt werken | weekend ook vaak in Sneek! Ze wil niet meer naar Wolvega vanwege de afstand. Niet veel bsb ivm drukte studie maar wil wel op de poule blijven"}'],
  ['Hidde Willebrandts','hidde@willebrandts.nl','06- 81871548','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "fysiek_zwaar": "1"}'],
  ['NIET BSB IVM STUDIE OF VAKANTIE','','Telefoon','{"rijbewijs": "In bezit van een rijbewijs: Schakel (RBW S) of Automaat RBW A)", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "photonis": "1", "afwas": "1", "barista": "1", "ass_keuken": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "cycloon": "1", "fysiek_zwaar": "1", "opmerkingen": "Data gerelateerde opmerkingen | Opmerkingen"}'],
  ['Mark Mous','markmous@icloud.com','06-26449535','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "horeca_toppers": "1", "catering": "1", "opmerkingen": "18 dec t/m 9 jan op wintersport"}'],
  ['Caitlin Luntz','caitlinluntz@gmail.com','06-12276067','{"nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "afwas": "1", "barista": "1", "housekeeping": "1", "opmerkingen": "GEEFT EEN SEINTJE WANNEER ZE BSB IS Buiten Groningen goed met haar doornemen!"}'],
  ['Michel Semturis','michel.semturis@gmail.com','0049-15732366331','{"nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "housekeeping": "1", "opmerkingen": "Michel was vorige week ziek | NIET TERUG KH/HM/REITSCHANS en Hamming niet terug | NIET TERUG KH/HM/REITSCHANS en Hamming niet terug, wil geen HK"}'],
  ['Viktoria Tuvi','vickie.tuvi@gmail.com','0037-25073428','{"rijbewijs": "nee", "nl_verstaan": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "opmerkingen": "wk 14 examens, 4 t/m 14 april in buitenland | FASE B !! WANNEER ZE VANAF NU 05012025  ELKE WEEK WERKT DAN PER 1502"}'],
  ['Maria Wallicka','mariawww2006@gmail.com','+48 509 070 705','{"nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Niet bsb ivm drukte met studie, geeft zelf aan wanneer wel bsb"}'],
  ['Fréderique Oldenhof','frederiquedenhof@outlook.com','06-15204927','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "NIET NAAR ASSEN | Op zondag niet naar Assen, helemaal niet meer voor HK"}'],
  ['Witte de Rijk','wittederijk@hotmail.com','06 2212 8630','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Jennifer Uhljar','uhljardzsenifer@gmail.com','36705796243','{"rijbewijs": "nee", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "tot 19 jan niet in Nederland | NOG GEEN GELDIG ID-BEWIJS ONTVANGEN, MAG NIET WERKEN"}'],
  ['Axel Warbroek','axel.warbroek@gmail.com','06-13334168','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "orderpicker": "1", "cycloon": "1", "fysiek_zwaar": "1"}'],
  ['Dennis van Driel','dendriel@icloud.com','06-3924005','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "afwas": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "Heeft vanaf 24 juni een andere functie"}'],
  ['Yasmine Rouendal van','y.a.van.rouendal@student.rug.nl','06-82690563','{"rijbewijs": "?", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "orderpicker": "1", "housekeeping": "1"}'],
  ['Oleksii Stolyar','oleksii.stolyar@gmail.com','06-29749038','{"rijbewijs": "nee", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1"}'],
  ['Dagmar Pluim','dagmar.pluim@gmail.com','06-83309323','{"rijbewijs": "?", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "plateau": "1", "rug": "1", "catering": "1", "opmerkingen": "hersenschudding, appt wanneer het goed gaat | Alleen in Groningen, wil niet naar Assen", "barista": "1"}'],
  ['Lilian Arnoldus','lilianarnoldus@gmail.com','06-37408873','{"rijbewijs": "?", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Annelie Bos','anneliesophiebos@gmail.com','06-83859369','{"rijbewijs": "?", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "stijlzinnig": "1", "barista": "1"}'],
  ['Remmelt Huizinga','remmelt04@gmail.com','06 2352 0382','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "fysiek_zwaar": "1", "opmerkingen": "bsb vanaf half juni weer | heeft te druk met studie en vaste bijbaan, wil halverwege juni graag weer in de poule"}'],
  ['Jan Kruithof','jjrkruithof@gmail.com','06-40488611','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "housekeeping": "1", "plateau": "1"}'],
  ['Ravi Maas','ravi.j.maas@gmail.com','06-38586371','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Tess Pouderoyen','tess.pouderoyen@hotmail.com','06-14218327','{"rijbewijs": "?", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Katie Vries de','katie.devries2008@gmail.com','06-31380245','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "Druk met studie en andere baan, geeft seintje als ze weer kan werken"}'],
  ['Stijn Brinksma','stijnbrinksma@gmail.com','06-22821221','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "cycloon": "1", "fysiek_zwaar": "1"}'],
  ['Joris van Driel','jordriel@icloud.com','06-30507757','{"rijbewijs": "BS", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "fysiek_zwaar": "1"}'],
  ['Nieki Eerdmans','niekieerdmans@gmail.com','06-83409857','{"rijbewijs": "BS", "eigen_auto": "1", "auto_regelen": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "photonis": "1", "afwas": "1", "barista": "1", "housekeeping": "1", "stijlzinnig": "1", "nl_spreken": "1", "nl_verstaan": "1", "opmerkingen": "reageert niet ook niet nadat je haar hebt gs | vakantie 1402 - 2102"}'],
  ['Jonas Knol-Bruins','jonasknolbruins@gmail.com','06-30830250','{"rijbewijs": "BS", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "housekeeping": "1", "stijlzinnig": "1", "fysiek_zwaar": "1", "barista": "1"}'],
  ['Nynke Leverman','nynkeleverman@outlook.com','06-28201187','{"rijbewijs": "?", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "plateau": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Chris Meulen van der','chrisvdmeulen04@gmail.com','06-44641380','{"rijbewijs": "nee", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "fysiek_zwaar": "1", "opmerkingen": "6 t/m 15 mrt  op wintersport"}'],
  ['Alex Plotnikov','alexpousplotnikov@gmail.com','+34 657358297','{"rijbewijs": "nee", "bar": "1", "catering": "1", "fysiek_zwaar": "1"}'],
  ['Yrsa Reuver','y.a.reuver@student.rug.nl','06-31281213','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Milan Vrij','milanvrijgrn2009@gmail.com','06-29432825','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "housekeeping": "1"}'],
  ['Reinout Fock','reinout@pukka.com','06-57964114','{"rijbewijs": "?", "nl_spreken": "1", "nl_verstaan": "1", "orderpicker": "1"}'],
  ['Casper Kamstra','casper.kamstra@icloud.com','06-23612534','{"rijbewijs": "mee bezig", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "fysiek_zwaar": "1"}'],
  ['Marrit Veer van der','marritvanderveer@ziggo.nl','06-11279491','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "horeca_toppers": "1", "opmerkingen": "Verder heb ik vakantie vanaf 20 juli tot en met 3 aug. Ik kan wel nog jullie forms blijven invullen hoor want na mijn vakantie sta ik gewoon aan voor beide:)"}'],
  ['Femke Wijnen','f.c.wijnen@gmail.com','06-29899173','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "stijlzinnig": "1", "opmerkingen": "wk 10 vakantie | Alleen naar Assen voor lange diensten"}'],
  ['Finn Feringa','stormartworks.design@gmail.com','06-45644295','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1", "fysiek_zwaar": "1"}'],
  ['Mirthe Janssen','mirthejanssen10@gmail.com','06-11667329','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Diana Korendijk','dianakorendijk@proton.me','06-83152585','{"rijbewijs": "BS", "catering": "1", "opmerkingen": "18 MAART NIET BSB | vanaf week 9 ALLEEN VOOR DE CATERINGGvZ  hebben wij ergens nood en zij is wel bsb dan wel vragen | vanaf week 9 ALLEEN VOOR DE CATERING, en dan in de eerste plaats GvZaken", "barista": "1"}'],
  ['Lotte Staring','lotte.staring@icloud.com','06-48068794','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "wk 11 vakantie"}'],
  ['Judith Jonge de','jldejonge7@gmail.com','06-10307570','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "6 t/m 14 mrt op wintersport", "barista": "1"}'],
  ['Amanda Leite','mallu_leitte@outlook.com','06-40260780','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "opmerkingen": "kan vanaf week 19 uit de poule"}'],
  ['Fenne Poel','fenne.poel@yahoo.com','06-23945585','{"rijbewijs": "?", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "VAKANTIE"}'],
  ['Finn Scheringa','stormartworks.design@gmail.com','06-45644295','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1", "fysiek_zwaar": "1"}'],
  ['Roosmarijn van Strien','roosmarijnvanstrien@gmail.com','06-57336971','{"rijbewijs": "BS", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "nl_spreken": "1", "nl_verstaan": "1"}'],
  ['Levi Timmer','timmerlevi@hotmail.com','06-12055521','{"rijbewijs": "?", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "cycloon": "1", "fysiek_zwaar": "1"}'],
  ['Shardé Bregitha','sharde.bregitha@gmail.com','06-634448369','{"rijbewijs": "B", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "housekeeping": "1", "afwas": "1", "opmerkingen": "v"}'],
  ['Tetiana Tarasenko','tartatyana23@gmail.com','06-27897907','{"rijbewijs": "nee", "housekeeping": "1", "opmerkingen": "Vast voor HK inplannen | Vast voor HK inplannen - gaat dinsdag goed bij Koops dan kan ze van de poule zo nog even ovb"}'],
  ['Mignon Withaar','mignonwithaar@gmail.com','06-55941124','{"rijbewijs": "BS", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "horeca_toppers": "1", "catering": "1", "barista": "1"}'],
  ['Sherriece Fleming','sherriecefleming@hotmail.com','06-45149203','{"nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Ruma Gerritsen','rumagerritsen@gmail.com','06-25381153','{"rijbewijs": "scooter", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "cycloon": "1", "opmerkingen": "2 - 3 dgn BW HK is voldoende voor haar | Wil niet meer naar de Bonte Wever Housekeeping"}'],
  ['Adnan Kucuksahin','','','{}'],
  ['Daantje Riddersma','daantjeriddersma@hotmail.com','06-15292848','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "photonis": "1", "opmerkingen": "Op reis van 17 mei tot 21 juni | Fulltime bsb ivm tussenjaar"}'],
  ['Emily Bernard','emily.r.bernard@icloud.com','06-21961267','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Glydsi Flores','glysdi25_flores@yahoo.com','06-43157729','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "plateau": "1", "rug": "1", "catering": "1", "opmerkingen": "Fulltime bsb ivm tussenjaar, wel alleen in Groningen"}'],
  ['Cecile zie regel hier onderaan dit tabblad, kan het niet kopieren Hoving','','','{}'],
  ['Ilse Hoekstra','ilse.hoekstra07@gmail.com','06-57522339','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Thom Jonge Poerink','thomjp2004@gmail.com','06-51151224','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "fysiek_zwaar": "1"}'],
  ['Viktoria FS B?? Tuvi','vickie.tuvi@gmail.com','0037-25073428','{"rijbewijs": "nee", "nl_verstaan": "1", "borden_3": "1", "plateau": "1", "rug": "1", "beijk_wolvega": "1", "catering": "1", "schoonmaak": "1", "opmerkingen": "wk 14 examens, 4 t/m 14 april in buitenland | FASE B !! WANNEER ZE VANAF NU 05012025  ELKE WEEK WERKT DAN PER 1502"}'],
  ['Yvan Bell','yvanpacobel@gmail.com','06-83558997','{"bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "catering": "1", "barista": "1", "schoonmaak": "1", "housekeeping": "1", "fysiek_zwaar": "1"}'],
  ['Karsten Bosch','karstenbosch@hotmail.com','06-36284460','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "fysiek_zwaar": "1", "opmerkingen": "Pols gebroken"}'],
  ['Vosse Bruinsma','vosse.bruinsma@gmail.com','615304342','{"rijbewijs": "scooter", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "fysiek_zwaar": "1"}'],
  ['Anne Vis','annexvis@gmail.com','06-57740837','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Jessica Robaard','jes.rob11@gmail.com','06-11492771','{"rijbewijs": "Bezig BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "barista": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "wk 15 VA 6 april bsb"}'],
  ['Karsten Bakker','kdbakker07@gmail.com','06-13984175','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "plateau": "1", "catering": "1", "orderpicker": "1", "fysiek_zwaar": "1", "opmerkingen": "wk 16 niet bsb"}'],
  ['Finn Brug van der','finnbrug12@gmail.com','06-39532150','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1"}'],
  ['Indira Bruni','indiracarlabruni@gmail.com','0039-3703213095','{"rijbewijs": "nee", "nl_verstaan": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "fysiek_zwaar": "1"}'],
  ['Rosalie Kleissen','rosaliekleissen@gmail.com','06-20020316','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "plateau": "1", "rug": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "VAKANTIE 2804/0505 daarna minder bsb tot 22 juni ivm invalwerk school oude stage 6 juni werkt ze wel | VAKANTIE 2804/0505 daarna minder bsb tot 22 juni ivm invalwerk school oude stage 6 juni werkt ze wel TAAK eind juni"}'],
  ['Noor Korts','noorkorts@gmail.com','06-27336564','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "photonis": "1"}'],
  ['Jace Mollenaar','jacemollema09@gmail.com','06-29428067','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "housekeeping": "1"}'],
  ['Leon Smit','leonsmit.ls@gmail.com','06-81194077','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "horeca_toppers": "1", "catering": "1", "housekeeping": "1"}'],
  ['Jorick Bakker','bakkerjorick07@gmail.com','06-18609114','{"rijbewijs": "BS", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "horeca_toppers": "1", "catering": "1"}'],
  ['Shardé VA 1704 BSB Bregitha','sharde.bregitha@gmail.com','06-634448369','{"rijbewijs": "B", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "housekeeping": "1"}'],
  ['Jits Jong de','jitsdej7@gmail.com','06-20956813','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "schoonmaak": "1"}'],
  ['Sieger Jan Klaarbergen van','siegerjanvanklaarbergen@gmail.com','06-15681845','{"rijbewijs": "scooter", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "stijlzinnig": "1", "fysiek_zwaar": "1"}'],
  ['Jace Mollema','jacemollema09@gmail.com','06-29428067','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "housekeeping": "1"}'],
  ['Casper Santen van','caspervansanten@gmail.com','06-38446302','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "orderpicker": "1", "stijlzinnig": "1"}'],
  ['Leon Spa','lbdspa@gmail.com','06-12657099','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "beijk_wolvega": "1", "catering": "1", "afwas": "1", "barista": "1", "ass_keuken": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Sherriece nog aanvullen Fleming','sherriecefleming@hotmail.com','06-45149203','{"opmerkingen": "Aankomende weken  vakantie/ Niet bsb", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Jan weer bsb? Ja dan aanvullen Kruithof','jjrkruithof@gmail.com','','{}'],
  ['Nienke Berg van den','nienke@moreservices.nl','06-33568226','{"bier_tappen": "1", "borden_3": "1", "plateau": "1", "catering": "1"}'],
  ['Diba Reints','dibareints@gmail.com','06-26455115','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bier_tappen": "1", "borden_3": "1", "catering": "1", "afwas": "1"}'],
  ['REMINDER gm 2204','','','{}'],
  ['Vasco Rodrigues','rodriguescfvasco@gmail.com','0035-1966888099','{"rijbewijs": "nee", "bar": "1", "borden_3": "1", "plateau": "1", "rug": "1", "catering": "1", "barista": "1", "housekeeping": "1", "opmerkingen": "VAKANIE 20-06 TOT SEP"}'],
  ['Sander Wijnia','sanderwijnia@gmail.com','06-27651971','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "afwas": "1", "orderpicker": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Roos Jong de','rozel2008@gmail.com','06-83663002','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "werkt na examens vanaf 24 mei VAKANTIE 04/06-08/06 en 27/07-03/08"}'],
  ['Oldenburg Britt','brittoldenburg11@gmail.com','brittoldenburg11@gmail.com','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "catering": "1", "photonis": "1", "barista": "1"}'],
  ['Tanya Sassu','tanyasassu@outlook.com','06-41477301','{"rijbewijs": "BS", "eigen_auto": "1", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['David Schaub','david_schaub@web.de','06-45476121','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "orderpicker": "1", "stijlzinnig": "1"}'],
  ['Ada Bordean','adaab3033@gmail.com','+40 773963721','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "catering": "1", "barista": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Brecht Dikkerboom','brecht.dikkerboom@gmail.com','06-51372765','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Olivier Huisers','olivier.huisers@gmail.com','06-12671706','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "stijlzinnig": "1", "fysiek_zwaar": "1", "opmerkingen": "Buiten groningen even checken of hij het wilt, geen HK assen"}'],
  ['Stef Knijnenburg','stefkn@outlook.com','06-83649809','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "rug": "1", "catering": "1", "barista": "1", "stijlzinnig": "1"}'],
  ['Rochelle Mooij','rochelle.mooij@live.com','06-22667317','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "borden_3": "1", "plateau": "1", "catering": "1", "barista": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "groningen, assen, roden en leek is prima, daarbuiten liever niet"}'],
  ['Mahour Nikpanjeh','mahniiik@gmail.com','06-633842961','{"rijbewijs": "nee nee", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1"}'],
  ['Fatimah Noureddine','fatimahnoureddine06@outlook.com','06-43789157','{"rijbewijs": "BS", "eigen_auto": "1", "nl_spreken": "1", "nl_verstaan": "1", "plateau": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1"}'],
  ['Shantelly Cecilia','shantydc@hotmail.com','06-82810443','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Dominique Dam de','dominique24.vandam@ziggo.nl','06-36433863','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "catering": "1", "opmerkingen": "buiten groningen in overleg"}'],
  ['Donya Naftchi','dnaftchi@gmail.com','06-68223888','{}'],
  ['Kirsten Olinga','kirsten-olinga@hotmail.com','06-12959372','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['David Roos','davidtuinroos@icloud.com','06-46614099','{"bar": "1", "bier_tappen": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "rijbewijs": "?", "nl_spreken": "1", "nl_verstaan": "1", "plateau": "1", "fysiek_zwaar": "1"}'],
  ['Beyene Harnet','harnetbeyene21@outlook.com','Bellen: 0686232525 / WhatsApp:06-48131979','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "catering": "1", "photonis": "1", "schoonmaak": "1", "opmerkingen": "VAKANTIE 0907-3107"}'],
  ['marèl Borghuis','','','{"bar": "1", "bier_tappen": "1", "plateau": "1", "catering": "1"}'],
  ['Dorinda van Bruggen','','','{"catering": "1", "schoonmaak": "1", "housekeeping": "1"}'],
  ['Sam Devroede','sam.devroede@hotmail.com','06-17035116','{"rijbewijs": "nee", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "catering": "1", "afwas": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "fysiek_zwaar": "1"}'],
  ['Johannes Lagerweij','johannes.lagerweij@live.nl','06-14308856','{"rijbewijs": "BS", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "horeca_toppers": "1", "catering": "1", "barista": "1"}'],
  ['Lars Maanen van','larsvanmaanen@icloud.com','06-48151509','{"rijbewijs": "BS", "auto_regelen": "1", "nl_spreken": "1", "nl_verstaan": "1", "bar": "1", "bier_tappen": "1", "borden_3": "1", "plateau": "1", "catering": "1", "schoonmaak": "1", "housekeeping": "1", "stijlzinnig": "1", "opmerkingen": "vakantie 10-26 juli | wilt geen horeca werk doen behalve catering, ook geen avond werk na (17:00)"}'],
  ['Donya Nafchti','dnaftchi@gmail.com','06-82223888','{}'],
  ['Tolga ulker','','','{"schoonmaak": "1", "housekeeping": "1"}'],
];


if (!$uitvoeren) {
    echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>PSP Vaardigheden Import</title>';
    echo '<style>body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:20px}.info{background:#d1ecf1;border:1px solid #bee5eb;padding:16px;border-radius:8px;margin:16px 0}.btn{display:inline-block;padding:12px 28px;background:#d31775;color:#fff;border-radius:8px;text-decoration:none;font-weight:700}</style>';
    echo '</head><body><h1>Vaardigheden import</h1>';
    echo '<div class=info>Studenten in Poule Excel: ' . count($poule_data) . '</div>';
    echo '<a class=btn href="?sleutel=pspvaardigheden2026&run=1">Uitvoeren</a></body></html>';
    exit;
}

// Uitvoeren
$ok = 0; $skip = 0; $nieuw_tel = 0;
foreach ($poule_data as [$naam, $email, $telefoon, $vaard_json]) {
    $vaardigheden = json_decode($vaard_json, true) ?: [];
    $wp_user = null;

    // Match op email (primair)
    if ($email) $wp_user = get_user_by('email', $email);

    // Match op display_name (fallback)
    if (!$wp_user && $naam) {
        $users = get_users(['search' => $naam, 'search_columns' => ['display_name']]);
        if ($users) $wp_user = $users[0];
    }

    // similar_text fallback
    if (!$wp_user && $naam) {
        $alle = get_users(['role__in' => ['psp_student', 'psp_aanvraag']]);
        $best = 0; $best_user = null;
        foreach ($alle as $u) {
            similar_text(strtolower($naam), strtolower($u->display_name), $p);
            if ($p > $best) { $best = $p; $best_user = $u; }
        }
        if ($best >= 70) $wp_user = $best_user;
    }

    if (!$wp_user) { $skip++; continue; }

    update_user_meta($wp_user->ID, 'psp_vaardigheden', $vaardigheden);
    if ($telefoon) update_user_meta($wp_user->ID, 'psp_telefoon', $telefoon);
    $ok++;
}

echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Klaar</title>';
echo '<style>body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:20px}.ok{background:#d4edda;border:1px solid #28a745;padding:16px;border-radius:8px;margin:8px 0}</style>';
echo '</head><body><h1>Vaardigheden import klaar</h1>';
echo "<div class=ok>✅ Bijgewerkt: {$ok}</div>";
echo "<div class=ok>⚠️ Niet gevonden: {$skip}</div>";
echo "<div class=ok><a href='" . home_url('/planning-dashboard/') . "'>Naar dashboard →</a></div>";
echo '</body></html>';
